Working GCS bucket
massdriver-cloud/gcp-gcs-bucket-application-assets pull request #1
Opened 2024-02-01 19:30 UTC by mclacore

2024-02-15 06:36 UTC, chrisghill requested changes
Some minor changes. Once made I'll approve.

Just to confirm, you tested both IAM policies and they work, correct?

2024-02-15 06:36 UTC, chrisghill commented on README.md
> +
Remove this line

2024-02-15 06:36 UTC, chrisghill commented on src/_providers.tf
> +provider "google-beta" {
you can remove this provider

2024-02-15 06:36 UTC, chrisghill commented on src/_providers.tf
> +    google-beta = {
you can remove this provider

2024-02-15 06:36 UTC, chrisghill commented on src/_providers.tf
> +    null = {
you can remove this provider

2024-02-15 19:45 UTC, mclacore commented
> Some minor changes. Once made I'll approve.
> 
> Just to confirm, you tested both IAM policies and they work, correct?

Yes, I tested creating a .txt file, and then read from it

2024-02-25 06:19 UTC, chrisghill approved these changes

2024-02-26 18:34 UTC, merged